
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 21 05:13:14 CDT 2017
//----------------------------------------------------

package scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 36;
  public static final int PLUSPLUS = 31;
  public static final int EQUALS = 40;
  public static final int CONTINUE = 48;
  public static final int GREATER = 43;
  public static final int LPAREN = 24;
  public static final int INT = 2;
  public static final int LESS = 42;
  public static final int FOR = 5;
  public static final int MINUS = 34;
  public static final int WRITE = 29;
  public static final int RPAREN = 25;
  public static final int AND = 38;
  public static final int NOT = 37;
  public static final int SEMICOLON = 26;
  public static final int OR = 39;
  public static final int BOOL = 6;
  public static final int COMMA = 27;
  public static final int PLUS = 33;
  public static final int ASSIGN = 46;
  public static final int LESSEQ = 44;
  public static final int MAIN = 4;
  public static final int IF = 14;
  public static final int DOT = 28;
  public static final int ID = 18;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 32;
  public static final int RETURN = 17;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int COMA = 7;
  public static final int LCURLY = 22;
  public static final int CIN = 12;
  public static final int BREAK = 47;
  public static final int VOID = 8;
  public static final int RCURLY = 21;
  public static final int INTLITERAL = 19;
  public static final int TIMES = 35;
  public static final int errorlex = 3;
  public static final int ELSE = 15;
  public static final int COUT = 13;
  public static final int READ = 30;
  public static final int NOTEQUALS = 41;
  public static final int WHILE = 16;
  public static final int FLOAT = 23;
  public static final int GREATEREQ = 45;
  public static final int STRINGLITERAL = 20;
  public static final int FALSE = 10;
  public static final int STRUCT = 11;
}

