
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 06 18:35:32 CDT 2017
//----------------------------------------------------

package scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 37;
  public static final int PLUSPLUS = 32;
  public static final int EQUALS = 41;
  public static final int GREATER = 44;
  public static final int LPAREN = 25;
  public static final int INT = 2;
  public static final int LESS = 43;
  public static final int MINUS = 35;
  public static final int FOR = 6;
  public static final int WRITE = 30;
  public static final int RPAREN = 26;
  public static final int AND = 39;
  public static final int NOT = 38;
  public static final int SEMICOLON = 27;
  public static final int OR = 40;
  public static final int BOOL = 7;
  public static final int COMMA = 28;
  public static final int PLUS = 34;
  public static final int ASSIGN = 47;
  public static final int LESSEQ = 45;
  public static final int MAIN = 5;
  public static final int IF = 15;
  public static final int DOT = 29;
  public static final int ID = 19;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 33;
  public static final int RETURN = 18;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int LCURLY = 23;
  public static final int CIN = 13;
  public static final int BREAK = 48;
  public static final int VOID = 9;
  public static final int RCURLY = 22;
  public static final int INTLITERAL = 20;
  public static final int TIMES = 36;
  public static final int errorlex = 3;
  public static final int ELSE = 16;
  public static final int COUT = 14;
  public static final int READ = 31;
  public static final int NOTEQUALS = 42;
  public static final int WHILE = 17;
  public static final int FLOAT = 24;
  public static final int FLOAR = 4;
  public static final int GREATEREQ = 46;
  public static final int STRINGLITERAL = 21;
  public static final int FALSE = 11;
  public static final int STRUCT = 12;
}

